### ISSUE TITLE
Need a button to navigate back to home page from `about` or a post

### ISSUE THREAD

**Issue by rmarow** [nsidc/nsidc.github.io#3]

**Comment by MattF-NSIDC** [comment]
What do you think, should we have top navigation like this:

https://qgreenland-workshop-2023-researcher.github.io/

Or sidebar navigation like this:

https://sael-swfsc.github.io/adrift-analysis-methods/

I don't have strong opinions, but I feel sidebar navigation is great for informational sites. Would it also work for a blog-type site? What about having both (too cluttered IMO)?

**Comment by rmarow** [comment]
@MattF-NSIDC I like the way it's done for QGreenland!

**Comment by MattF-NSIDC** [comment]
Click the GitHub logo on the top-right of the page and it'll take you there :) 

https://github.com/qgreenland-workshop-2023-researcher/qgreenland-workshop-2023-researcher.github.io

**Comment by rmarow** [comment]
Completed in this commit: 5505dfddc0e40792e117871c3acb4d93bd608593
